// examples/angular-client/src/app.component.ts
import { Component, inject, signal } from "@angular/core";
import {
  VexaMediaService,
  VexaPreviewService,
  VexaRenderService,
  type VexaJobRef,
  type VexaMediaAsset,
  type VexaRenderResult,
  type VexaVideoRenderRequest
} from "@vexa-video/angular";

@Component({
  selector: "vexa-example-app",
  standalone: true,
  template: `
    <main>
      <h1>Vexa Angular example</h1>
      <input type="file" accept="video/*" (change)="upload($event)">
      <button type="button" [disabled]="!asset()" (click)="render()">Render 720p</button>
      @if (asset(); as media) {
        <video controls [src]="preview.url(media)" style="max-width: 720px; width: 100%"></video>
      }
      @if (job(); as current) {
        <pre>{{ current.state() }} · {{ current.progress()?.percent ?? 0 }}%</pre>
      }
    </main>
  `
})
export class AppComponent {
  private readonly media = inject(VexaMediaService);
  private readonly renders = inject(VexaRenderService);
  readonly preview = inject(VexaPreviewService);
  readonly asset = signal<VexaMediaAsset | null>(null);
  readonly job = signal<VexaJobRef<VexaVideoRenderRequest, VexaRenderResult> | null>(null);

  async upload(event: Event): Promise<void> {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    this.asset.set(await this.media.upload(file));
  }

  async render(): Promise<void> {
    const asset = this.asset();
    if (!asset) return;
    this.job.set(await this.renders.renderVideo({
      mediaId: asset.id,
      operations: [{ type: "resize", options: { width: 1280, height: 720, fit: "contain" } }],
      outputFormat: "mp4",
      export: { videoCodec: "h264", audioCodec: "aac", hardwareAcceleration: "auto" }
    }));
  }
}

// examples/vue-client/src/App.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue";

const baseUrl = "http://127.0.0.1:4190";
const file = ref<File | null>(null);
const mediaId = ref<string | null>(null);
const job = ref<any>(null);
let timer: number | undefined;

const outputUrl = computed(() => job.value?.result?.outputUrl
  ? new URL(job.value.result.outputUrl, baseUrl).toString()
  : null);

function choose(event: Event) {
  file.value = (event.target as HTMLInputElement).files?.[0] ?? null;
}

async function upload() {
  if (!file.value) return;
  const response = await fetch(`${baseUrl}/v1/media`, {
    method: "POST",
    headers: {
      "content-type": file.value.type || "application/octet-stream",
      "x-vexa-file-name": file.value.name
    },
    body: file.value
  });
  const media = await response.json();
  if (!response.ok) throw new Error(media.error ?? "Upload failed");
  mediaId.value = media.id;
}

async function render() {
  if (!mediaId.value) return;
  const response = await fetch(`${baseUrl}/v1/jobs`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      type: "video.render",
      payload: {
        mediaId: mediaId.value,
        operations: [{ type: "resize", options: { width: 1280, height: 720, fit: "contain" } }],
        outputFormat: "mp4",
        export: { videoCodec: "h264", audioCodec: "aac", hardwareAcceleration: "auto" }
      }
    })
  });
  job.value = await response.json();
  if (!response.ok) throw new Error(job.value.error ?? "Render submission failed");
  timer = window.setInterval(async () => {
    const status = await fetch(`${baseUrl}/v1/jobs/${job.value.descriptor.id}`);
    if (!status.ok) return;
    job.value = await status.json();
    if (["succeeded", "failed", "cancelled"].includes(job.value.state)) {
      window.clearInterval(timer);
      timer = undefined;
    }
  }, 500);
}

onBeforeUnmount(() => {
  if (timer !== undefined) window.clearInterval(timer);
});
</script>

<template>
  <main>
    <h1>Vexa Vue example</h1>
    <input type="file" accept="video/*" @change="choose">
    <button :disabled="!file" @click="upload">Upload</button>
    <button :disabled="!mediaId" @click="render">Render 720p</button>
    <p v-if="job">{{ job.state }} · {{ job.progress?.percent ?? 0 }}%</p>
    <video v-if="outputUrl" controls :src="outputUrl" style="width:100%;max-width:800px" />
  </main>
</template>
